#!/usr/bin/env bash
#
# Description: Display an alert based on it's importance
# Dependency: wget

# Set to none
var="none"

# Check if dac connected
dac=`cat /proc/asound/cards | grep "DAC" | head -1 | awk '{ print $6 }'`
dac=${dac,,}
[ -n "$dac" ] && var=$dac

stat=`iw dev wlp4s0 link | grep SSID | awk '{print $2}'`

if [[ $stat == "" ]]
then
	echo "noip"
else
	echo "wifi"
fi
