#!/usr/bin/env bash
#
# Description: Display the battery level or status

percent=`cat /sys/class/power_supply/BAT1/capacity`
power=`cat /sys/class/power_supply/BAT1/status`
	
if [[ $power == "Charging" ]]
then
	echo "eat"
elif [[ $percent == 100 ]]
then
	echo "ful"
else
	echo ${percent}%
fi
